//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AktywniWWW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageUser
    {
        public int MessageUserID { get; set; }
        public int UserID { get; set; }
        public int MessageID { get; set; }
        public bool IsOpened { get; set; }
        public Nullable<int> UserFromID { get; set; }
    
        public virtual Messages Messages { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
