//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AktywniWWW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageEvent
    {
        public int MessageEventID { get; set; }
        public int EventID { get; set; }
        public int MessageID { get; set; }
        public int UserFromID { get; set; }
        public bool IsOpened { get; set; }
        public Nullable<int> UserToId { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Messages Messages { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
