//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AktywniWWW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObjectComments
    {
        public int CommentID { get; set; }
        public int UserID { get; set; }
        public int ObjectID { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Objects Objects { get; set; }
        public virtual Users Users { get; set; }
    }
}
